spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test_schema?serverTimezone=Asia/Seoul
    username: root
    password: 1q2w3e4r!
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate.ddl-auto: update
    properties.hibernate.format_sql: true